install.packages("devtools")
library(devtools)
install_github("ohdsi/SqlRender")
install_github("ohdsi/DatabaseConnector")
install_github("ohdsi/OhdsiSharing")
#install_github("ohdsi/FeatureExtraction")
install_github("ohdsi/FeatureExtraction", dependencies = TRUE, INSTALL_opts = '--no-lock')
install_github("ohdsi/CohortMethod")
install_github("ohdsi/EmpiricalCalibration")
install_github("ohdsi/MethodEvaluation")
devtools::install_github("ohdsi-studies/Covid19EstimationHydroxychloroquine")