---
title: "Publication - Results"
author: "CAKU"
date: "`r Sys.Date()`"
output: html_document
---

# Publication - Results

```{r include=FALSE}
options(scipen=999)
library(pacman)
pacman::p_load(openxlsx,
               dplyr,
               data.table,
               tidyr,
               glue,
               scales,
               lubridate,
               openxlsx,
               ggplot2)
```

# Paths

```{r}

path_exportedResults = "~/EFPIA-RWD-SUBMISSION-PILOT/exportedResults"
path_dqdJsonFiles = "~/EFPIA-RWD-SUBMISSION-PILOT/dqdJsonFiles"
path_comparison = "~/EFPIA-RWD-SUBMISSION-PILOT/comparison"

# Output folders
path_cms_synpuf="/EFPIA-RWD-SUBMISSION-PILOT/Data/OHDSI/CMS_SynPuf"
path_evidera_output="/EFPIA-RWD-SUBMISSION-PILOT/Data/Evidera/98_output"
path_vocab="/EFPIA-RWD-SUBMISSION-PILOT/Data/OHDSI/OMOP/02_Vocabulary/Standard_Vocabulary_v5"
path_logs="/EFPIA-RWD-SUBMISSION-PILOT/logs"
path_ranalysis="/EFPIA-RWD-SUBMISSION-PILOT/Output/RANALYSIS"

```

# SynPuf Source

```{r}

df_synpuf =
  file.info( list.files(path = path_cms_synpuf,full.names = T,recursive = TRUE) ) %>% 
  dplyr::mutate(filename=row.names(.)) %>% 
  dplyr::select(filename,size) %>% 
  dplyr::mutate(filename=gsub("/EFPIA-RWD-SUBMISSION-PILOT/Data/OHDSI/CMS_SynPuf/","",filename)) %>% 
  filter(!grepl('DE_0/|.zip|.srt',filename)) %>% 
  dplyr::mutate(group=gsub("/","",stringr::str_match(filename,"DE_\\d.*/"))) %>% 
  dplyr::mutate(type=gsub("_\\d.*","",filename)) %>% 
  dplyr::mutate(number=gsub(".csv|.txt","",stringr::str_match(filename,"\\d.*"))) %>% 
  dplyr::select(-filename) 

```

All gigabyte numbers.

```{r}
df_synpuf %>% 
  group_by(group) %>% 
  dplyr::summarise(size=sum(size)/1000000000) %>% 
  filter(!is.na(group)) %>% 
  dplyr::mutate(total=scales::number(sum(size),accuracy = 0.01),
                min=scales::number(min(size),accuracy = 0.01),
                max=scales::number(max(size),accuracy = 0.01),
                size=scales::number(size,accuracy = 0.01)) %>% 
  knitr::kable()
```

# ETL Output

```{r}

df_etl = file.info( list.files(path = path_evidera_output,full.names = T) ) %>% 
  dplyr::mutate(filename=row.names(.)) %>% 
  dplyr::select(filename,size) %>% 
  dplyr::mutate(filename=gsub("/EFPIA-RWD-SUBMISSION-PILOT/Data/Evidera/98_output/","",filename)) %>% 
  dplyr::mutate(type=gsub("_\\d.*","",filename)) %>% 
  dplyr::mutate(number=gsub(".csv|.txt","",stringr::str_match(filename,"\\d.*"))) %>% 
  dplyr::select(-filename) %>% 
  filter(!number==0)

```

## Conversion sizes of portions

```{r}
df_etl %>% 
  group_by(number) %>% 
  dplyr::summarise(size=sum(size)/1000000000) %>% 
  filter(!is.na(number)) %>% 
  dplyr::mutate(total=scales::number(sum(size),accuracy = 0.01),
                min=scales::number(min(size),accuracy = 0.01),
                max=scales::number(max(size),accuracy = 0.01),
                size=scales::number(size,accuracy = 0.01)) %>% 
  arrange(number) %>% 
  knitr::kable()
```

## Data by OMOP area

```{r}
df_etl %>% 
  group_by(type) %>% 
  dplyr::summarise(size=sum(size)/1000000000) %>% 
  filter(!is.na(type)) %>% 
  dplyr::mutate(total=scales::number(sum(size),accuracy = 0.01),
                min=scales::number(min(size),accuracy = 0.01),
                max=scales::number(max(size),accuracy = 0.01),
                size=scales::number(size,accuracy = 0.01)) %>% 
  arrange(type) %>% 
  knitr::kable()
```

## Person ID count

```{r}

person_files = df_etl %>% 
  filter(grepl("person",type)) %>% 
  row.names(.) 

df_person_id = rbindlist(lapply(person_files,function(person_file) {
    data.frame(file=person_file,person_id=read.csv(file = person_file)$person_id)
  })) %>% 
  distinct()

df_person_id %>% 
  group_by(file) %>% 
  dplyr::summarise(count=length(unique(person_id))) %>% 
  dplyr::mutate(total=sum(count),
                min=min(count),
                max=max(count))
```

## Observation Length

```{r}

observation_period_files = df_etl %>% 
  filter(grepl("observation_period",type)) %>% 
  row.names(.) 

df_observation_periods = rbindlist(lapply(observation_period_files,function(observation_period_file) {
    read.csv(file = observation_period_file) %>% 
                 dplyr::mutate(observation_period_start_date=ymd(observation_period_start_date),
                               observation_period_end_date=ymd(observation_period_end_date)) %>% 
                 dplyr::mutate(length=as.integer(observation_period_end_date-observation_period_start_date)) %>% 
    dplyr::mutate(file=observation_period_file) %>% 
    relocate(file)
  })) %>% 
  distinct() %>% 
  dplyr::mutate(file=gsub("/EFPIA-RWD-SUBMISSION-PILOT/Data/Evidera/98_output/","",file))

df_observation_periods %>% 
  dplyr::mutate(length=length/365.25) %>% 
  group_by(file) %>% 
  dplyr::summarise(count=length(unique(person_id)),
                   sum_length=sum(length,na.rm=T)) %>% 
  dplyr::mutate(total_person_ids=sum(count),
                total_length=sum(sum_length)) %>% 
  dplyr::mutate(avg_length=total_length/total_person_ids)
```

# Results Analysis Summary

```{r}
df_results_nn = read.csv(file = "/EFPIA-RWD-SUBMISSION-PILOT/Output/RANALYSIS_FTP/analysisSummary.csv")
```

```{r}
# Total
df_results_nn %>% 
  group_by(analysisId,analysisDescription) %>% 
  dplyr::summarise(total_analyses=length(analysisId),
                   non_na=sum(!is.na(rr)))
```

```{r}
df_results_nn %>% 
  group_by(outcomeId,outcomeName) %>% 
  dplyr::summarise(count=n())
```

```{r}
df_results_nn %>% 
  group_by(outcomeId,outcomeName,
           comparatorId,comparatorName) %>% 
  dplyr::summarise(count=n())
```
```{r}
df_results_nn %>% 
  group_by(comparatorId,comparatorName,
           targetId,targetName) %>% 
  dplyr::summarise(count=n())
```
```{r}
df_results_nn %>% 
  group_by(targetId,targetName) %>% 
  dplyr::summarise(count=n())
```

```{r}
df_results_nn %>% 
  group_by(outcomeId,outcomeName,
           comparatorId,comparatorName,
           targetId,targetName) %>% 
  dplyr::summarise(count=n())
```

# Results Cohort Counts

```{r}

read.csv(file = "/EFPIA-RWD-SUBMISSION-PILOT/Output/RANALYSIS_FTP/CohortCounts.csv") %>% 
  arrange(desc(personCount)) %>% 
  dplyr::mutate(personCount=log10(personCount)) %>% 
  dplyr::mutate(cohortName=stringr::str_trunc(cohortName,50)) %>% 
  dplyr::mutate(cohortName=factor(cohortName,levels=rev(unique(.$cohortName)))) %>% 
  ggplot(.,aes(x=cohortName,y=personCount)) +
  geom_col(size=0.4) +
  coord_flip() +
  labs(title="Fig X: Person Count by Cohort",
       x=NULL,
       y="Subject Count (Log10)") +
  theme_bw() +
  scale_y_continuous(breaks=c(0,1,2,3,4,5,6),labels=c("0","10","100","1 000","10 000","100 000","1 000 000")) +
  theme(axis.text.y = element_text(size=6))
```

# Results Comparison

```{r}
df_comparison_result = openxlsx::read.xlsx(xlsxFile = glue("{path_comparison}/comparison_results.xlsx"))
```

## SE log of RR

```{r}

# Differences in results
results <- df_comparison_result %>%
  rename(valueDKMA = `/EFPIA/EFPIA-RWD-SUBMISSION-PILOT/exportedResults//ResultsDKMA/ResultsDKMA_FTP.zip`,
         valueJNJ = `/EFPIA/EFPIA-RWD-SUBMISSION-PILOT/exportedResults//siteJnJ/UsingJnJetlAndRenv.zip`,
         valueNN = `/EFPIA/EFPIA-RWD-SUBMISSION-PILOT/exportedResults//siteNN/ResultsNN.zip`) %>%
  dplyr::select( target_id : stat , valueDKMA , valueJNJ , valueNN ) %>% 
  filter(stat == "se_log_rr") %>% 
  gather(site,val,valueDKMA:valueNN) %>% 
  group_by( target_id , comparator_id , outcome_id , analysis_id , stat ) %>% 
  dplyr::mutate(sd_=sd(val),
                mean_=mean(val)) %>% 
  dplyr::mutate(lwr=mean_-qnorm(p = 0.975)*sd_,
                upr=mean_+qnorm(p = 0.975)*sd_)

# Visualize

p1 = results %>%
  dplyr::mutate(site=recode(site, 'valueDKMA' = 'Site 1',   'valueJNJ' = 'Site 2',  'valueNN'='Site 3')) %>% 
  filter(!is.na(mean_)) %>% 
  filter(outcome_id <= 22) %>% 
  unite(target_id,target_id,comparator_id,outcome_id,analysis_id) %>% 
  arrange(mean_) %>% 
  dplyr::mutate(target_id=factor(target_id,levels=rev(unique(.$target_id)))) %>% 
  ggplot(.,aes(x=target_id,y=mean_)) +
  geom_point(alpha=0.3) +
  geom_point(aes(y=val,shape=site),alpha=0.3) +
  coord_flip() +
  geom_errorbar(aes(ymin=lwr,ymax=upr),alpha=0.3,width=0.3) +
  labs(title="Fig X: Uniformity of Final Analysis Results Across Sites",
       x=NULL,
       y="Log Standard Error Relative Risk (95%CI)") +
  theme_bw() +
  theme(legend.position="top")+
  scale_y_continuous(breaks=c(seq(0,1,by=0.1),seq(1,2.0,by=0.25)),limits=c(0,NA)) +
  scale_x_discrete(labels=NULL)

p1

ggsave(filename = "p1.png",plot = p1,device = "png",width = 20,height=20)

```

## Subject count

```{r eval=F}

# Differences in results
results <- df_comparison_result %>%
  rename(valueDKMA = `/EFPIA/EFPIA-RWD-SUBMISSION-PILOT/exportedResults//ResultsDKMA/ResultsDKMA_FTP.zip`,
         valueJNJ = `/EFPIA/EFPIA-RWD-SUBMISSION-PILOT/exportedResults//siteJnJ/UsingJnJetlAndRenv.zip`,
         valueNN = `/EFPIA/EFPIA-RWD-SUBMISSION-PILOT/exportedResults//siteNN/ResultsNN.zip`) %>%
  dplyr::select( target_id : stat , valueDKMA , valueJNJ , valueNN ) %>% 
  filter(stat %in% c("comparator_subjects","target_subjects","comparator_days","target_days")) %>% 
  gather(site,val,valueDKMA:valueNN) %>% 
  separate(stat,into=c("group","statistics")) %>% 
  dplyr::mutate(val=log10(val))

# Visualize

p2 = results %>%
  dplyr::mutate(site=recode(site, 'valueDKMA' = 'Site 1',   'valueJNJ' = 'Site 2',  'valueNN'='Site 3')) %>% 
  # filter(outcome_id <= 22) %>% 
  unite(target_id,target_id,comparator_id,outcome_id,analysis_id) %>% 
  spread(statistics,val) %>% 
  ggplot(.,aes(x=days,y=subjects)) +
  geom_point(alpha=0.3) +
  geom_point(aes(y=val,shape=site),alpha=0.3) +
  coord_flip() +
  geom_errorbar(aes(ymin=lwr,ymax=upr),alpha=0.3,width=0.3) +
  labs(title="Fig X: Uniformity of Final Analysis Results Across Sites",
       x=NULL,
       y="Log Standard Error Relative Risk (95%CI)") +
  theme_bw() +
  theme(legend.position="top")+
  scale_y_continuous(breaks=c(seq(0,1,by=0.1),seq(1,2.0,by=0.25)),limits=c(0,NA)) +
  scale_x_discrete(labels=NULL)

p2

ggsave(filename = "p2.png",plot = p2,device = "png",width = 2000,height=2000,units = "px")



```

# Propensity Matching

```{r}

results_paths = list.files(path = path_exportedResults,recursive = TRUE,full.names = TRUE)

results_pm = do.call("rbind", lapply(results_paths,function(path) {
  tmp_dir = tempdir(check = TRUE)
  unzip(zipfile = path,exdir = tmp_dir)
  tmp_df = read.csv( list.files(path = tmp_dir, pattern = "propensity_model.csv",recursive = TRUE,full.names = TRUE) )
  tmp_df$database_id = NULL
  tmp_df$path = path
  unlink(tmp_dir, recursive = T)
  return(tmp_df)
})) %>% 
  dplyr::mutate(path=gsub("/home/oem/EFPIA-RWD-SUBMISSION-PILOT/exportedResults/","",path))

# Find any differences
results_pm_sd <- results_pm %>%
  arrange(analysis_id,target_id,comparator_id,covariate_id,path) %>% 
  group_by(analysis_id,target_id,comparator_id,covariate_id) %>% 
  summarise(sd = sd(coefficient)) %>%
  filter(sd > 0) %>% 
  arrange(desc(sd)) %>% 
  unite(analysis_id,analysis_id,target_id,comparator_id,covariate_id) %>% 
  dplyr::mutate(analysis_id=factor(analysis_id,levels=rev(unique(.$analysis_id))))
# Visualize

p3 = results_pm_sd %>%
  ggplot(.,aes(x=analysis_id,y=sd)) +
  geom_point(alpha=0.3) +
  coord_flip() +
  labs(title="Fig X: Propensity Score Matching Uniformity of Coefficients",
       x=NULL,
       y="SD of Coefficients") +
  theme_bw() +
  theme(legend.position="top",axis.text.y = element_blank())

# p3

ggsave(filename = "p3.png",plot = p3,device = "png",width = 20,height=20)

```





# Data Quality Dashboards

```{r eval=F}

path_dqdJsonFiles
```
